version: '3'

services:
  spark-master:
    image: haihp02/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
    # networks:
    #   - spark-hdfs-network
    # extra_hosts:
    #   - "namenode:20.239.82.205"
    #   - "datanode1:20.239.82.205"
    #   - "datanode2:20.239.82.205"
    #   - "datanode3:20.239.82.205"

  spark-worker-1:
    image: haihp02/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    # networks:
    #   - spark-hdfs-network
    # extra_hosts:
    #   - "namenode:20.239.82.205"
    #   - "datanode1:20.239.82.205"
    #   - "datanode2:20.239.82.205"
    #   - "datanode3:20.239.82.205"

  spark-worker-2:
    image: haihp02/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    # networks:
    #   - spark-hdfs-network
    # extra_hosts:
    #   - "namenode:20.239.82.205"
    #   - "datanode1:20.239.82.205"
    #   - "datanode2:20.239.82.205"
    #   - "datanode3:20.239.82.205"

  spark-worker-3:
    image: haihp02/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    # networks:
    #   - spark-hdfs-network
    # extra_hosts:
    #   - "namenode:20.239.82.205"
    #   - "datanode1:20.239.82.205"
    #   - "datanode2:20.239.82.205"
    #   - "datanode3:20.239.82.205"

# networks:
#   spark-hdfs-network:
#     external: true